### ISSUE TITLE
Theming shadow-root / custom elements

### ISSUE THREAD

**Issue by nullishamy** [thunderbird/webext-experiments#27]
Hi there. Apologies if this isn't the right place for this. I maintain a theme for Thunderbird ([catppuccin/thunderbird](https://github.com/catpuccin/thunderbird)) and have recently come across some UI elements that appear to be unthemeable 🤔 .

I have a tracking issue (https://github.com/catppuccin/thunderbird/issues/10) which is trying to track these elements, but I am curious if there is a way to theme them. If so, I'd like to know. If not, I'd like to request there be a way to do it!

Thanks

**Comment by kewisch** [comment]
Check out https://developer.thunderbird.net/add-ons/web-extension-themes#theme-experiments which could help you create WebExtension theme properties for custom CSS. The best place to get in touch is here, if you have further questions: https://developer.thunderbird.net/add-ons/community
