### ISSUE TITLE
experiment does not unload

### ISSUE THREAD

**Issue by opto** [thunderbird/webext-experiments#47]
I just tried a number of commits and noticed that unload/load addon does not work.

I can load another version with a restart of TB and -purgecache (maybe the latter is not needed).

This may need the query parameter when loading modules, as we discussed in element recently?

**Comment by kewisch** [comment]
Yeah, likely makes sense. I didn't bother to fix it for now, in 128 I needed to make some changes that brought this error back. If query parameters are the way we're fixing this for other experiments then let's get that added as well.

**Comment by jobisoft** [comment]
This is fixed by https://github.com/thunderbird/webext-experiments/pull/53
