### ISSUE TITLE
calendar experiment is using fixed resource path "resource://tb-experiments-calendar/"

### ISSUE THREAD

**Issue by jobisoft** [thunderbird/webext-experiments#52]
If two add-ons use this experiment, but different versions, they both will access the *same* file (overwriting each other's definitions) and one of them will break, if the content of the file is not as expected.

A possible way around this: Add a revision prefix to the path: `resource://tb-experiments-calendar-v12/` which gets increased with each commit to the repository. Other ideas?

**Comment by kewisch** [comment]
I really wish there was a more specific way to do this. I think I had to go back to the resurce:// url because resolving the moz-extension:// url to a file/jar url caused a security error.

Let's just get this into core so people don't need to use it? ;-)

Lighthearted humor aside, I think the v12 approach is probably the best short term solution. Another option would be to include some code in the repo that throws an error if the developer kept it at tb-experiments-calendar, which forces them to change it to their own identifier.

**Comment by jobisoft** [comment]
Regardless of the reported issue, we also run into this:
https://developer.thunderbird.net/add-ons/mailextensions/experiments#structuring-experiment-code

And the proposed solution is:

```
const { ExtensionParent } = ChromeUtils.importESModule(
    "resource://gre/modules/ExtensionParent.sys.mjs"
);
const extension = ExtensionParent.GlobalManager.getExtension(
    "<id-of-your-extensions>"
);
const query = extension.manifest.version;

// Load TestModule.sys.mjs.
var { TestModule } = ChromeUtils.importESModule(
  "resource://myaddon/TestModule.sys.mjs?" + query
)

```

I think we can combine this to not only add the additional query, but also make the path unique. I will come up with something. I wish detecting the calling add-on would be possible somehow...

**Comment by jobisoft** [comment]
Could @LouisJULIEN give the patched experiment a deep dive with his add-on (Create Calendar events from mail content)? Does it still work or did I miss something?

**Comment by LouisJULIEN** [comment]
@jobisoft Yes sure! 

Just to make sure I understood correctly: you would like me to replace the experiment's code I'm using in my Thunderbird Extension with the code in this [PR](https://github.com/thunderbird/webext-experiments/pull/53/files) and make sure everything works for me as before. Am I right?

**Comment by jobisoft** [comment]
> [@jobisoft](https://github.com/jobisoft) Yes sure!
> 
> Just to make sure I understood correctly: you would like me to replace the experiment's code I'm using in my Thunderbird Extension with the code in this [PR](https://github.com/thunderbird/webext-experiments/pull/53/files) and make sure everything works for me as before. Am I right?

Yes. You can check out branch "issue52":
https://github.com/thunderbird/webext-experiments/tree/issue52

**Comment by LouisJULIEN** [comment]
I tested [it](https://github.com/LouisJULIEN/thunderbird_plugin_mail_to_event), looks good to me!

**Comment by LouisJULIEN** [comment]
If I may, it seems a bit weird to me that the isolation is handled at experiment level and not at Thunderbird level. It makes it easy for a developer, even of good faith, to make a similar mistake in the future.

**Comment by jobisoft** [comment]
The answer to that is probably "it is what it is". The experiment mechanism is something we inherit from Mozilla and the overall platform is removing features to reduce technical debt:
* moz-extension:// paths (specific to an extension) can no longer be used for loading system modules, but only global paths
* loaded system modules can no longer be unloaded and are cached aggressively (usually a module implementation is only changed on Firefox/Thunderbird update followed by a restart, and not "hot" as it can happen for Experiments)

I think the tweak introduced in this PR deals with it in the best possible way. We do (try to) document this:
https://developer.thunderbird.net/add-ons/mailextensions/experiments#structuring-experiment-code

The issue with the global path is only relevant for shared Experiments (as this one). In general, I require unique global path definitions during add-on review (where we caught this issue as well).

**Comment by LouisJULIEN** [comment]
Thanks for your answer. With that in mind, your design choice seems relevant.
